name: stellaris
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  image_picker: "^0.4.1"
  json_annotation: ^0.2.3
  cached_network_image: "^0.4.1"
  flutter_secure_storage: "^3.0.0"
  scoped_model: "^0.3.0"
  flutter_fetch_widget: "^0.0.1+1"
  shared_preferences: "^0.4.2"
  dio: "^1.0.9"
  flutter_sparkline: "^0.1.0"
  carousel_slider: "^0.0.6"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  async_loader: "^0.1.1"
  json_serializable: ^0.5.0
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: true 
  ios: "Example-Icon"
  image_path: "assets/icon.png"
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/logo.jpeg
    - assets/icon.png
    - assets/white-logo.png
    - assets/ETHEREUM-ICON_Black_small.png
    - assets/BC_Logo_.png
    - assets/Twitter_avatar.png
    - assets/filecoin.png
    - assets/Storj-symbol.png
    - assets/ipfs.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Medium.ttf
        - asset: assets/Montserrat-Regular.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
